### ISSUE TITLE
SH1106 draw image

### ISSUE THREAD

**Issue by hu53yin** [costonisp/ESP8266-I2C-OLED#5]
Hello, 

How can I draw an 1bpp bmp picture, from hex data to 1.3" oled screen with SH1106 driver?

I use that function but this is not correctly working.
# define offset 0x02

const char WIFI1[] PROGMEM = {..........
................................some..hex..data.......
};

clear_display();
setXY(0,0);
// Display Logo here :)
for(int i=0;i<128*_8;i++)     // show 128_ 64 Logo
{
    SendChar(pgm_read_byte(WIFI1+i));
}
sendcommand(0xaf);      //display on

**Comment by costonisp** [comment]
This will only work with the exclusive SSD1306 library and not in this sketch that uses a modified SSD1306 library.
